= Demo for setting up Confluent Platform with CP Flink using KIND (Kubernetes in Docker)

This demo show how to set up Confluent Platform with CP Flink using KIND (Kubernetes in Docker).

== Preconditions

You need to have the following software installed:

* docker: https://www.docker.com/
* kind: https://kind.sigs.k8s.io/
* kubectl: Depends on your platform
* helm: https://helm.sh/

This setup instanciates some heavy components using quite a lot of memory and cpu. We recommend using a node with lots of RAM and multiple (virtual) cores.

Once the cluster is up and running, you can check the status of the kubernetes single node (which runs in docker) like this:

```console
kubectl describe nodes | grep -E "(Name:|Resource|memory)"
kubectl describe nodes | grep -E "(Name:|Resource|cpu)"
```

Recommendation: Use 8 cores and at least 32 GiB of RAM.
Alternatively, you can just run a f subset of the available components.

== Setting up the infrastructure

Run the `start.sh` script.

```console
kubectl get pods
```

== Usage

You can run kafka commands locally as usual. Please make sure to have these lines in your /etc/hosts file, though:

```console
127.0.0.1   kafka mds schemaregistry flink controlcenter ksqldb
::1         kafka mds schemaregistry flink controlcenter ksqldb
```

Alternatively, you can run commands directly in a kubernetes pod which is deleted once you log out:

```console
kubectl run kafka-cli -i --tty --image=docker.io/confluentinc/cp-server:8.2.1 -
-restart=Never --rm -- bash
```

List topics as usual:

```console
kafka-topics --bootstrap-server kafka:9092 --list
```

Check the status of the KRaft controller:

```console
kafka-metadata-quorum --bootstrap-server kafka:9092 describe --status
```

You can connect to control center with your browser via (make sure you have deleted the HTTP test described above):

* http://controlcenter/ (this makes use of SNI, make sure you have updated your `/etc/hosts`), or
* http://localhost:9021/ (direct TCP connection to control center, no SNI)

=== Kafka connect

This demo consists of a Kafka Connect cluster which can download and use the Datagen Source Connector from the Confluent Hub.

Create a topic `users` with default setting. Then head over to your Connect cluster and create a Datagen Source connector.
Use `users` as value for the `kafka.topic` field and `users` as value for the `quickstart` field.

Start the connect and watch the events being produced to the topic.

For more options, please have a look at the documentation here: https://docs.confluent.io/cloud/current/connectors/cc-datagen-source.html


=== Flink Applications

In the following, a few example applications are deployed.

You can list the existing Flink environments like this:

```console
confluent flink environment list --url http://flink
```

The applications in an existing environment can be listed like this:

```console
confluent flink application list --environment env1 --url http://flink
```

Note: Flink is integrated in Control Center: http://controlcenter

==== Basic Example

Create environment:

```console
confluent flink environment create env1 --url http://flink:80 --kubernetes-namespace flink
```

Create basic demo application:

```console
confluent flink application create flink/application-basic-example.json --environment env1 --url http://flink:80
```

After a while, the webui for monitoring the Flink application can be made available on http://localhost:8090 like this:

```console
confluent flink application web-ui-forward basic-example --environment env1 --port 8090 --url http://flink
```

Delete the application:

```console
confluent flink application delete basic-example --environment env1 --url http://flink
```

=== ksqlDB

Create a topic called `orders` using Confluent Cloud Console.

Produce some automatically generated messages to that topic.

Open a ksqlDB terminal, either in Confluent Control Center, or using this command:

```console
kubectl exec -ti ksqldb-0 -- ksql
```

In ksqlDB, you first need to register a stream for that topic:

```console
CREATE STREAM orders (
  ordertime BIGINT,
  orderid   INT,
  itemid    STRING,
  address   STRUCT<
    city STRING,
    state STRING,
    zipcode INT
  >
) WITH (
  KAFKA_TOPIC = 'orders',
  VALUE_FORMAT = 'JSON'
);
```

Then you can query the stream:

```console
SELECT * FROM orders EMIT CHANGES;
```

== Debugging the Setup

=== Traefik

Traefik is used for routing ingress HTTP and TCP connections.

You can access the dashboard here: http://traefik/

== Shutting down your resources

```console
kind delete cluster
```
