= Demo for setting up Confluent Platform with CP Flink using KIND (Kubernetes in Docker)

This demo show how to set up Confluent Platform with CP Flink using KIND (Kubernetes in Docker).

== Preconditions

You need to have the following software installed:

* docker: https://www.docker.com/
* kind: https://kind.sigs.k8s.io/
* kubectl: Depends on your platform
* helm: https://helm.sh/
* confluent cli: https://docs.confluent.io/confluent-cli/current/install.html

Additionally required packages to be installed via local distribution-specific package manager

* curl

This setup instanciates some heavy components using quite a lot of memory and cpu. We recommend using a node with lots of RAM and multiple (virtual) cores.

Once the cluster is up and running, you can check the status of the kubernetes single node (which runs in docker) like this:

```console
kubectl describe nodes | grep -E "(Name:|Resource|memory)"
kubectl describe nodes | grep -E "(Name:|Resource|cpu)"
```

Recommendation: Use 8 cores and at least 32 GiB of RAM.
Alternatively, you can just run a f subset of the available components.

Please make sure to have these lines in your /etc/hosts file, though:

```console
127.0.0.1   kafka mds schemaregistry flink controlcenter ksqldb s3storage
::1         kafka mds schemaregistry flink controlcenter ksqldb s3storage
```

== Setting up the infrastructure

Run the `./start.sh` script.

```console
kubectl get pods
```

=== If running in a restrictive environment

If this setup needs to be used in a restricted environment where container images cannot be used directly but only through a proxy, please edit `start.sh` and enable the aliases pointing all requests to your enterprise image registry instead of the original sources.

We need to distinguish two things: First, the `kind` cluster is bootstrapped by using an image called `kindest/node:v1.35.0` in docker. The version number might differ, please check by running `kind version`.

When setting up kind initially, the image `kindest/node:v1.35.0` needs to be available in the container image mirror registry.

Update the `start.sh`. file to 


Make sure you have all images in that enterprise image repository.

== Usage


Alternatively, you can run commands directly in a kubernetes pod which is deleted once you log out:

```console
kubectl run kafka-cli -i --tty --image=docker.io/confluentinc/cp-server:8.2.1 -
-restart=Never --rm -- bash
```

List topics as usual:

```console
kafka-topics --bootstrap-server kafka:9092 --list
```

Check the status of the KRaft controller:

```console
kafka-metadata-quorum --bootstrap-server kafka:9092 describe --status
```

You can connect to control center with your browser via (make sure you have deleted the HTTP test described above):

* http://controlcenter/ (this makes use of SNI, make sure you have updated your `/etc/hosts`), or
* http://localhost:9021/ (direct TCP connection to control center, no SNI)

=== Kafka connect

This demo consists of a Kafka Connect cluster which can download and use the Datagen Source Connector from the Confluent Hub.

Create a topic `users` with default setting. Then head over to your Connect cluster and create a Datagen Source connector.
Use `users` as value for the `kafka.topic` field and `users` as value for the `quickstart` field.

Start the connect and watch the events being produced to the topic.

For more options, please have a look at the documentation here: https://docs.confluent.io/cloud/current/connectors/cc-datagen-source.html


=== Flink Applications

In the following, a few example applications are deployed.
Note, the `confluent` CLI works with both Confluent Cloud and Confluent Platform. If you are working in a hybrid setup where you have both, make sure to logout via `confluent logout` from Confluent Cloud before using the CLI for accessing Confluent Platform. The `--url` is mandatory when accessing Confluent Platform with the CLI.

You can list the existing Flink environments like this:

```console
confluent flink environment list --url http://flink
```

The applications in an existing environment can be listed like this:

```console
confluent flink application list --environment myenv --url http://flink
```

Note: Flink is integrated in Control Center: http://controlcenter

==== Basic Example

Create environment (this shouldn't be required as the script will create that environment for you automatically):

```console
confluent flink environment create myenv --url http://flink --kubernetes-namespace flink
```

===== Flink Interactive

You can have an interactive Flink session using the `confluent` CLI. Just run:

```console

```



===== Flink Statements

===== Flink Application

Create basic demo application:

```console
confluent flink application create flink/application-basic-example.json --environment myenv --url http://flink
```

After a while, the webui for monitoring the Flink application can be made available on http://localhost:8090 like this:

```console
confluent flink application web-ui-forward basic-example --environment myenv --port 8090 --url http://flink
```

Delete the application:

```console
confluent flink application delete basic-example --environment myenv --url http://flink
```

=== ksqlDB

Create a topic called `orders` using Confluent Cloud Console.

Produce some automatically generated messages to that topic.

Open a ksqlDB terminal, either in Confluent Control Center, or using this command:

```console
kubectl exec -ti ksqldb-0 -- ksql
```

In ksqlDB, you first need to register a stream for that topic:

```console
CREATE STREAM orders (
  ordertime BIGINT,
  orderid   INT,
  itemid    STRING,
  address   STRUCT<
    city STRING,
    state STRING,
    zipcode INT
  >
) WITH (
  KAFKA_TOPIC = 'orders',
  VALUE_FORMAT = 'JSON'
);
```

Then you can query the stream:

```console
SELECT * FROM orders EMIT CHANGES;
```

== Flink

You can access via Control Center or on the command line.

On the command line, use this:

```console
confluent --url http://flink --environment myenv --compute-pool mypool flink shell
```

Some resources have been pre-configured for you:

* An environment as a container for your statements and applications
* A compute pool for executing statements
* A catalog pointing to the local Confluent Platform Schema Registry
* A database representing the local Confluent Platform Kafka cluster

Run a few statements for testing things:

```sql
show catalogs;
```

```sql
show databases;
```

```sql
show tables;
```

Let's query the orders topic (note: you need to leave the window open as results of this continuous query are only visible once):

```sql
select * from orders;
```

Now let's do some real stream processing.

First, select only events with certain characteristics and write them to a second topic:

```sql
select * from orders;
```

Let's check how the table has been created:

```sql
SHOW CREATE TABLE orders;
```

Note that the DDL output of the `address` field is truncated. In order to see the full result, run this on the command line:

```console
confluent --url http://flink --environment myenv --compute-pool mypool flink statement create ddl-orders --output json --sql "SHOW CREATE TABLE orders" | jq -r '.result.results.data[0].row[0]'
confluent --url http://flink --environment myenv flink statement delete "ddl-orders" --force
```

```sql
CREATE TABLE `mycatalog`.`mykafka`.`large_orders` (
  `key` VARBINARY(2147483647),
  `ordertime` BIGINT NOT NULL,
  `orderid` INT NOT NULL,
  `itemid` VARCHAR(2147483647) NOT NULL,
  `orderunits` DOUBLE NOT NULL,
  `address` ROW<`city` VARCHAR(2147483647) NOT NULL, `state` VARCHAR(2147483647) NOT NULL, `zipcode` BIGINT NOT NULL> NOT NULL
) DISTRIBUTED BY (`key`) INTO 1 BUCKETS
WITH (
  'scan.bounded.mode' = 'unbounded',
  'scan.startup.mode' = 'earliest-offset',
  'changelog.mode' = 'append',
  'kafka.cleanup-policy' = 'delete',
  'connector' = 'confluent',
  'value.format' = 'avro-registry',
  'key.format' = 'raw'
);
```

You will see a new topic in Kafka called `large_orders`.

Let's add some data to it:

```sql
INSERT INTO large_orders SELECT * from orders where orderunits>=5.0;
```


You can find more details in our documentation: https://docs.confluent.io/cp-flink/current/jobs/sql-statements/overview.html

== Debugging the Setup


=== Identifying all used container images including their sources

Run this command:

```console
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c
```

If you just want the list of images, use this command:

```console
kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c | awk '{print $2}'
```


Note, that some sources do not start with a hostname. In these cases, the default hostname `docker.io` is used.


=== Traefik

Traefik is used for routing ingress HTTP and TCP connections.

You can access the dashboard here: http://traefik/

== Shutting down your resources

```console
kind delete cluster
```
