= Demo for setting up Confluent Platform with CP Flink using KIND (Kubernetes in Docker)

This demo show how to set up Confluent Platform with CP Flink using KIND (Kubernetes in Docker).

== Preconditions

You need to have the following software installed:

* docker: https://www.docker.com/
* kind: https://kind.sigs.k8s.io/
* kubectl: Depends on your platform
* helm: https://helm.sh/

== Setting up the infrastructure

Run the `start.sh` script.

```console
kubectl get pods
```

== Usage

You can run kafka commands locally as usual. Please make sure to have these lines in your /etc/hosts file, though:

```console
127.0.0.1   kafka mds schemaregistry flink
::1         kafka mds schemaregistry flink
```

Alternatively, you can run commands directly in a kubernetes pod which is deleted once you log out:

```console
kubectl run kafka-cli -i --tty --image=docker.io/confluentinc/cp-server:8.2.1 -
-restart=Never --rm -- bash
```

List topics as usual:

```console
kafka-topics --bootstrap-server kafka:9092 --list
```

Check the status of the KRaft controller:

```console
kafka-metadata-quorum --bootstrap-server kafka:9092 describe --status
```

You can connect to control center with your browser via http://control-center/ (make sure you have deleted the HTTP test described above).


=== Flink Applications

In the following, a few example applications are deployed.

You can list the existing Flink environments like this:

```console
confluent flink environment list --url http://flink
```

The applications in an existing environment can be listed like this:

```console
confluent flink application list --environment env1 --url http://flink
```

==== Basic Example

Create environment:

```console
confluent flink environment create env1 --url http://flink:80 --kubernetes-namespace flink
```

Create basic demo application:

```console
confluent flink application create flink/application-basic-example.json --environment env1 --url http://flink:80
```

After a while, the webui for monitoring the Flink application can be made available on http://localhost:8090 like this:

```console
confluent flink application web-ui-forward basic-example --environment env1 --port 8090 --url http://flink
```

Delete the application:

```console
confluent flink application delete basic-example --environment env1 --url http://flink
```

== Debugging the Setup

=== Traefik

Traefik is used for routing ingress HTTP and TCP connections.

You can access the dashboard here: http://traefik/

== Shutting down your resources

```console
kind delete cluster
```
