/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ibm.flink.examples;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FlinkAppTest {
    @Test void dummy() {
        FlinkApp classUnderTest = new FlinkApp();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        assertNotNull("Hello World!", "Dummy test to ensure that the project is set up correctly");
    }
}
