# This will set up a docker proxy which caches images from hub.docker.com and a few other sources.
# We use this for simulating an enterprise network where images need to be fetched from an internal mirror as docker and kubernetes are not allowed to use original images from the internet directly.

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
        - 18081:8081
        - 15001:15001 # proxy: docker.io
        - 15002:15002 # proxy: quay.io
        - 15003:15003 # proxy: registry.k8s.io
    volumes:
        - nexus-data:/nexus-data

volumes:
  nexus-data:
