= Experiments with Confluent Schema Registry

== Building the code

Building the code using gradle:

```console
./gradlew build
```

Potentially, you might need to update gradle first:

```console
gradle wrapper
```

== Running the code

First, start the docker environment:

```console
docker compose up -d
```

First, set the compatilibity level of our subject to "FORWARD_TRANSITIVE":

```console
curl -X PUT -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"compatibility": "FORWARD_TRANSITIVE"}' \
http://localhost:8081/config/topic-value
```

Register the schema:

```console
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"namespace\": \"models.avro\", \"type\": \"record\", \"name\": \"SimpleValue\", \"fields\": [ {\"name\": \"theName\", \"type\": \"string\"}, {\"name\": \"theValue\", \"type\": \"string\"}, {\"name\": \"theNewName\", \"type\": \"string\"}]}"}' \
http://schemaregistry:8081/subjects/topic-value/versions
```

Run producer with gradle:

```console
./gradlew java-producer:run --args="../config/producer.properties"
```

If you want to produce unlimited many messages, use this:

```console
./gradlew java-producer:run --args="-c -1 ../config/producer.properties"
```

The producer also understands the option `-w <time in ms>` or `--wait <time in ms>`. This specifies the time to wait between producing messages. Default is to wait 1000 ms (1 second). Set to `0` to disable.

Run consumer with:

```console
./gradlew :java-consumer:run --args="../config/consumer.properties"
```

=== Client Metrics with KIP-714

You can enable the integrated extended monitoring features which have been implemented in KIP-714 on the broker side like this:

```console
kafka-client-metrics --bootstrap-server <broker-addres:broker-port> --alter --name <subscription_name> --metrics <metric_name_prefix> --interval <interval_ms>
```

For enabling monitoring for our Java producer for a specific metric, i.e. `org.apache.kafka.producer.record`, do the following:

```console
kafka-client-metrics --bootstrap-server broker:9092 --alter --name java-producer-record-metrics --metrics "org.apache.kafka.producer.record" --interval 10000
```

Let's enable all metrics instead:

```console
kafka-client-metrics --bootstrap-server broker:9092 --alter --name all-metrics --metrics "*" --interval 10000
```

List all configured metrics:

```console
kafka-client-metrics --bootstrap-server broker:9092 --list
```

In a separate terminal, run the producer:

```console
./gradlew :java-consumer:run --args="../config/consumer.properties"
```

Point your browser to `http://prometheus/`. 


== Helpful tools

=== Schema Registry


Get all known versions of the schema:

```console
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions
```

Inspect a specific version (here: version 1):

```console
curl -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1
```

Soft delete a specific version:

```console
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1
```

Permanently delete a specific version (you need to soft delete first):

```console
curl -X DELETE -H "Content-Type: application/vnd.schemaregistry.v1+json" http://localhost:8081/subjects/topic-value/versions/1?permanent=true
```


=== CLI Consumer

Read messages via CLI tools, using standard console consumer:

```console
kafka-console-consumer --bootstrap-server broker:9092 --topic java --from-beginning
```

Read messages via avro console consumer:

```console
kafka-avro-console-consumer --bootstrap-server broker:9092 --property schema.registry.url=http://schemaregistry:8081 --topic java --from-beginning
```

You might want to delete the topic to start fresh between tests:

```console
 kafka-topics --bootstrap-server broker:9092 --delete --topic java
```

Alternatively, if you just want to consume the same messages again with the Java consumer, just reset the consumer groups offset:

```console
kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --reset-offsets --to-earliest --topic java --execute
```

You can view the offsets by running:

```console
kafka-consumer-groups --bootstrap-server broker:9092 --group Consumer --describe
```

== Experimenting

== Development

Check for dependency updates in each of the sub projects like this:

```console
./gradlew -P java-producer dependencyUpdates -Drevision=release
```

Upgrade the dependency manually.

For upgrading the gradle version, you can use this:

```console
gradle wrapper --gradle-version <gradle version>
```

Show all dependencies:

```console
./gradlew -p java-producer dependencies
```


== Shutting down, deleting containers

```console
docker compose down -v
```

