/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.ben-manes.versions") version "0.54.0"
    id("com.gradleup.shadow") version "9.6.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }
}

// See ../gradle/libs.versions.toml for dependency versions
dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly(libs.junit.platform.launcher)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.flink.table.api)
    implementation(libs.flink.table.api.bridge.java)
    //implementation(libs.confluent.flink.core)
    implementation(libs.confluent.flink.table.api.java.plugin)

    // Flink Core (Provided by cluster)
    //compileOnly("org.apache.flink:flink-streaming-java:$flinkVersion")
    //compileOnly("org.apache.flink:flink-clients:$flinkVersion")
    compileOnly(libs.flink.streaming)
    compileOnly(libs.flink.clients)

    // Kafka Connector (Bundled into Shadow JAR)
    implementation(libs.flink.connector.kafka)

    // Logging
    runtimeOnly(libs.slf4j)
    runtimeOnly(libs.log4j)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    // We are not enforcing a specific Java version here
    //toolchain {
    //    languageVersion = JavaLanguageVersion.of(21)
    //}
}

application {
    // Define the main class for the application.
    mainClass = "com.ibm.flink.examples.FlinkApp"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

/*tasks.withType<com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask> {
    resolutionStrategy {
        componentSelection {
            // Explicitly declare the type of the selection parameter
            all { selection: ComponentSelection -> 
                fun String.isNonStable(): Boolean {
                    val stableKeywords = listOf("RELEASE", "FINAL", "GA")
                    val isStableKeyword = stableKeywords.any { this.uppercase().contains(it) }
                    val isSemantic = this.matches(Regex("^[0-9,.v-]+(-r)?$"))
                    return !isStableKeyword && !isSemantic
                }

                if (selection.candidate.version.isNonStable()) {
                    selection.reject("Release candidate")
                }
            }
        }
    }
}*/

tasks.named<DependencyUpdatesTask>("dependencyUpdates").configure {
    rejectVersionIf {
        val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { candidate.version.uppercase().contains(it) }
        val regex = "^[0-9,.v-]+(-r)?$".toRegex()
        val isStable = stableKeyword || regex.matches(candidate.version)
        !isStable
    }
}

tasks.named<com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask>("dependencyUpdates") {
    notCompatibleWithConfigurationCache("gradle-versions-plugin invokes JavaBasePlugin at execution time")
}

tasks.named<com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask>("dependencyUpdates").configure {
    filterConfigurations = org.gradle.api.specs.Spec<Configuration> { 
        !it.name.startsWith("incrementalScalaAnalysis") 
    }
}