/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ibm.flink.examples;

import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.api.DataTypes;
import org.apache.flink.table.api.EnvironmentSettings;
import static org.apache.flink.table.api.Expressions.$;
import static org.apache.flink.table.api.Expressions.lit;
import org.apache.flink.table.api.Schema;
import org.apache.flink.table.api.Slide;
import org.apache.flink.table.api.Table;
import org.apache.flink.table.api.TableDescriptor;
import org.apache.flink.table.api.TableEnvironment;

public class FlinkApp {

    private Schema createSchema() {

        Schema schema = Schema.newBuilder()
                .column("window_start", DataTypes.TIMESTAMP().notNull())
                .column("window_end", DataTypes.TIMESTAMP().notNull())
                .column("min_orderunits", DataTypes.DOUBLE().notNull())
                .column("max_orderunits", DataTypes.DOUBLE().notNull())
                .column("mean_orderunits", DataTypes.DOUBLE().notNull())
                .build();
        return schema;
    }

    public void run() {
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        TableEnvironment tableEnv = TableEnvironment.create(
                EnvironmentSettings.newInstance().inStreamingMode().build()
        );

        // First, we create the target topic for the statistics results
        TableDescriptor target_table = TableDescriptor.forConnector("confluent")
                .schema(createSchema())
                .option("key.format", "avro-registry") // Schema Registry format for keys
                .option("value.format", "avro-registry") // Schema Registry format for values
                .option("scan.startup.mode", "earliest-offset")
                .option("kafka.retention.time", "72h") // CMF lifecycle config
                .distributedBy(3, "user_id") // Bucket/partition strategy
                .build();

        tableEnv.createTable("orders-statistics-last-hour", target_table);

        // 3. Directly reference the source topic name as a Table (Schema is auto-inferred)
        Table source_table_orders = tableEnv.from("orders");

        // 4. Perform transformations using Table API
        Table windowedMetrics = source_table_orders
                .window(
                        Slide.over(lit(60).minutes())
                                .every(lit(1).minutes())
                                .on($("ordertime"))
                                .as("slidingWindow")
                )
                // 3. Group by the key and the defined window object
                .groupBy($("slidingWindow"))
                // 4. Calculate metrics and select window tracking bounds
                .select(
                        $("slidingWindow").start().as("window_start"),
                        $("slidingWindow").end().as("window_end"),
                        $("orderunits").min().as("min_orderunits"),
                        $("orderunits").max().as("max_orderunits"),
                        $("orderunits").avg().as("mean_orderunits"));

        // 5. Directly write to your target topic name without DDL
        windowedMetrics.insertInto("orders-statistics-last-hour").execute();
    }

    public static void main(String[] args) {
        new FlinkApp().run();
    }
}
